# # - name: Install Apache
# #   apt:
# #     name:
# #       - apache2
# #       # - unzip
# #     update_cache: yes
# #     state: latest


# # - name: copy index.php file
# #   copy:
# #     # src: "files/{{ file_name }}.zip"
# #     src: index/index.php
# #     dest: /var/www/html/

# # # - name: Modify Apache configuration file
# # #   become: true
# # #   lineinfile:
# # #     path: '/etc/apache2/sites-available/000-default.conf'
# # #     regexp: '^Documentroot.*$'
# # #     line: 'Documentroot /var/www/html/index.php'
  
# # # - name: restart Apache
# # #   become: true
# # #   service:
# # #     name: apache2
# # #     enabled: yes
# # #     state: restarted


# - name: Install Apache
#   apt:
#     name:
#       - apache2
#     update_cache: yes
#     state: latest


# - name: copy index.html file
#   copy:
#     # src: "files/{{ file_name }}.zip"
#     src: index/index.sh
#     dest: /var/www/html/
#     mode: +x


# # - name: copy index.html file
# #   copy:
# #     # src: "files/{{ file_name }}.zip"
# #     src: index/index.html
# #     dest: /var/www/html/

# # - name: copy script.js file
# #   copy:
# #     # src: "files/{{ file_name }}.zip"
# #     src: index/script.js
# #     dest: /var/www/html/

# # - name: copy get_ip.php file
# #   copy:
# #     # src: "files/{{ file_name }}.zip"
# #     src: index/get_ip.php
# #     dest: /var/www/html/


    
# - name: restart Apache
#   service:
#     name: apache2
#     enabled: yes
#     state: restarted

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Start Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Create index.html file
  shell: echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
  args:
    executable: /bin/bash
